# Generated by Django 3.2.5 on 2021-08-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumlev', models.IntegerField()),
                ('region', models.IntegerField()),
                ('division', models.IntegerField()),
                ('state', models.IntegerField()),
                ('county', models.IntegerField()),
                ('stname', models.CharField(max_length=128)),
                ('ctyname', models.CharField(max_length=128)),
                ('census2010pop', models.IntegerField()),
                ('estimatesbase2010', models.IntegerField()),
                ('popestimate2010', models.IntegerField()),
                ('popestimate2011', models.IntegerField()),
                ('popestimate2012', models.IntegerField()),
                ('popestimate2013', models.IntegerField()),
                ('popestimate2014', models.IntegerField()),
                ('popestimate2015', models.IntegerField()),
                ('popestimate2016', models.IntegerField()),
                ('popestimate2017', models.IntegerField()),
                ('popestimate2018', models.IntegerField()),
                ('popestimate2019', models.IntegerField()),
                ('popestimate042020', models.IntegerField()),
                ('popestimate2020', models.IntegerField()),
            ],
            options={
                'unique_together': {('state', 'county')},
            },
        ),
    ]
