# Generated by Django 3.2.5 on 2021-08-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscensus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='popestimate2020',
            field=models.IntegerField(null=True),
        ),
    ]
