# Generated by Django 3.2.5 on 2021-08-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='US',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('cases', models.BigIntegerField()),
                ('deaths', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'US',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=32)),
                ('fips', models.IntegerField()),
                ('cases', models.BigIntegerField()),
                ('deaths', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('date', 'state')},
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('county', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=32)),
                ('fips', models.IntegerField(null=True)),
                ('cases', models.BigIntegerField()),
                ('deaths', models.BigIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'unique_together': {('date', 'state', 'fips')},
            },
        ),
    ]
