# Generated by Django 3.2.5 on 2021-08-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidgeo', '0002_countyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCovid',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('county', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=32)),
                ('fips', models.IntegerField()),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('geoid', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=128)),
                ('statefp', models.IntegerField()),
                ('census2010pop', models.IntegerField()),
                ('popestimate2019', models.IntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name='countyinfo',
            table='county_info',
        ),
    ]
