# Generated by Django 3.2.5 on 2021-09-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidgeo', '0003_auto_20210828_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countyinfo',
            options={'managed': False, 'verbose_name_plural': 'County Info'},
        ),
        migrations.AlterModelOptions(
            name='stateinfo',
            options={'managed': False, 'verbose_name_plural': 'State Info'},
        ),
    ]
