# Generated by Django 3.2.5 on 2021-09-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidgeo', '0004_auto_20210904_0106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stateinfo',
            table='state_info',
        ),
    ]
